version: '3.8'
services:
  web:
    build:
      context: ./front-end
    restart: on-failure
    container_name: music-remoter
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SITE=${SITE}
    networks:
      - out
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.music.entrypoints=websecure"
      - "traefik.http.routers.music.rule=Host(`music.itsp3.space`)"
      - "traefik.http.routers.music.tls=true"
      - "traefik.http.routers.music.tls.certresolver=production"
      - "traefik.http.routers.music.middlewares=authelia@docker"

networks:
  out:
    name: traefik_default
    external: true