name: Deploy to Alteza

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Docker Container
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SITE: ${{ vars.SITE }}
        run: docker compose up -d --build
